### ISSUE TITLE
list inside forms

### ISSUE THREAD

**Issue by pierr** [get-focus/focus-redux#25]
As seen together on last thursday
- [x] Add a `listFor` helper in the form helpers
- [x] Add a `ListWrapper` which simulates a field but deal with all the list informations
  - [x] I should provide an `onChange` which can be called by a line update the list with the lisne content and then `dispatch` the new list as an input change
  - [x] same logic for the onBlur (formatter in action)

@Bernardstanislas can you add the photo of the board in this issue.
@Ephrame good luck with this!

**Comment by Ephrame** [comment]
https://github.com/get-focus/focus-redux/pull/29
